version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: student_management_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_management
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - student-management-network

  app:
    build: .
    container_name: student_management_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/student_management
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - student-management-network

networks:
  student-management-network:
